ut cherry-pick --skip" to skip this patch)   (use "git cherry-pick --abort" to cancel the cherry-pick operation)
  Changes not staged for commit:
    (use "git add <file>..." to update what will be committed)
      (use "git restore <file>..." to discard changes in working
      directory)
              modified:   backend/database.sqlite

	      Untracked files:
	        (use "git add <file>..." to include in what will be
		committed)
		        .env.test

			no changes added to commit (use "git add" and/or
			"git commit -a")
			PS
			C:\Users\bhutite\projects\My\portpolio_projects\assignment>
			git pull
			There is no tracking information for the current
			branch.
			Please specify which branch you want to merge
			with.
			See git-pull(1) for details.

			    git pull <remote> <branch>

			    If you wish to set tracking information for
			    this branch you can do so with:

			        git branch
				--set-upstream-to=origin/<branch>
				feature

				PS
				C:\Users\bhutite\projects\My\portpolio_projects\assignment>
				# Go back to master
				PS
				C:\Users\bhutite\projects\My\portpolio_projects\assignment>
				git checkout master
				error: Your local changes to the
				following files would be overwritten by
				checkout:
				        backend/database.sqlite
					Please commit your changes or
					stash them before you switch
					branches.
					Aborting
					PS
					C:\Users\bhutite\projects\My\portpolio_projects\assignment>
					PS
					C:\Users\bhutite\projects\My\portpolio_projects\assignment>
					# Create 'test' branch from
					before the last commit
					PS
					C:\Users\bhutite\projects\My\portpolio_projects\assignment>
					git checkout -b test 24d6159
					error: Your local changes to the
					following files would be
					overwritten by checkout:
					        backend/database.sqlite
						Please commit your
						changes or stash them
						before you switch
						branches.
						Aborting
						PS
						C:\Users\bhutite\projects\My\portpolio_projects\assignment>
						PS
						C:\Users\bhutite\projects\My\portpolio_projects\assignment>
						# Cherry-pick the
						documentation commit
						PS
						C:\Users\bhutite\projects\My\portpolio_projects\assignment>
						git cherry-pick ca6db5c
						On branch feature
						You are currently
						cherry-picking commit
						ca6db5c.
						  (all conflicts fixed:
						  run "git cherry-pick
						  --continue")
						    (use "git
						    cherry-pick --skip"
						    to skip this patch)
						      (use "git
						      cherry-pick
						      --abort" to cancel
						      the cherry-pick
						      operation)

						      Changes not staged
						      for commit:
						        (use "git add
							<file>..." to
							update what will
							be committed)
							  (use "git
							  restore
							  <file>..." to
							  discard
							  changes in
							  working
							  directory)
							          modified:
								  backend/database.sqlite

								  Untracked
								  files:
								    (use
								    "git
								    add
								    <file>..."
								    to
								    include
								    in
								    what
								    will
								    be
								    committed)
								            .env.test

									    no
									    changes
									    added
									    to
									    commit
									    (use
									    "git
									    add"
									    and/or
									    "git
									    commit
									    -a")
									    The
									    previous
									    cherry-pick
									    is
									    now
									    empty,
									    possibly
									    due
									    to
									    conflict
									    resolution.
									    If
									    you
									    wish
									    to
									    commit
									    it
									    anyway,
									    use:

									        git
										commit
										--allow-empty

										Otherwise,
										please
										use
										'git
										cherry-pick
										--skip'
										PS
										C:\Users\bhutite\projects\My\portpolio_projects\assignment>
										PS
										C:\Users\bhutite\projects\My\portpolio_projects\assignment>
										#
										Push
										this
										branch
										PS
										C:\Users\bhutite\projects\My\portpolio_projects\assignment>
										git
										push
										origin
										test
										error:
										src
										refspec
										test
										does
										not
										match
										any
										error:
										failed
										to
										push
										some
										refs
										to
										'https://github.com/tenzin333/ai-studio.git'
										pdated aiusage and openapi.yaml files